### ISSUE TITLE
WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403

### ISSUE THREAD

**Issue by vverloop** [Automattic/pinghub#8] opened 2017-11-01 11:03 UTC
WebSocket connection to 'wss://public-api.wordpress.com/pinghub/wpcom/me/newest-note-data' failed: Error during WebSocket handshake: Unexpected response code: 403

I use Directadmin Custombuild: Nginx as Reverse Proxy + Apache.

Since a few days i get this error. Something has changed, but can't find it.

**Comment by vverloop** [comment] 2017-11-01 11:07
It looks like it has something to do with HTTP/2 and Nginx as a Reverse Proxy.
That the connection can't be upgraded to HTTP/2.
But my connection is upgraded to HTTP/2.

➜  ~ curl -I https://www.xxx.nl
HTTP/2 200 
server: nginx
date: Wed, 01 Nov 2017 11:07:00 GMT
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
expires: Wed, 01 Nov 2017 11:45:50 GMT
pragma: public
cache-control: max-age=2330, public
x-powered-by: W3 Total Cache/0.9.5.4
link: <https://www.xxx.nl/wp-json/>; rel="https://api.w.org/", <https://wp.me/xxx-u>; rel=shortlink
set-cookie: wfvt_4186914189=59f9aad47cfdc; expires=Wed, 01-Nov-2017 11:37:00 GMT; Max-Age=1800; path=/; secure; HttpOnly
last-modified: Wed, 01 Nov 2017 10:45:50 GMT
etag: "31300a4a13e6b7dd798ef8ec2273bb7d"
vary: User-Agent

**Comment by vverloop** [comment] 2017-11-01 11:16
My Google Chrome is up-to-date
Version 62.0.3202.75 (Official build) (64-bits)
Mac OSX High Sierra

**Comment by vverloop** [comment] 2017-11-01 11:33
<img width="687" alt="schermafbeelding 2017-11-01 om 12 30 38" src="https://user-images.githubusercontent.com/1451713/32272985-cf2a9bda-bf00-11e7-8065-34c77434ca6d.png">

**Comment by ErikThiart** [comment] 2018-01-02 21:36
Same issue

**Comment by edco100** [comment] 2018-01-08 09:52
Same here!

**Comment by alexhaller** [comment] 2018-01-09 18:32
Same problem here.

**Comment by Gtrujillo** [comment] 2018-01-11 12:13
Also have this issue

**Comment by smark73** [comment] 2018-01-11 15:49
Same issue

**Comment by softtama** [comment] 2018-01-13 02:25
Having this same issue!

**Comment by sDoka** [comment] 2018-01-15 19:36
Same problem

**Comment by jakenoble** [comment] 2018-01-16 23:03
Same here, the rate that this is happening to others seems to be increasing?

**Comment by jvmonjo** [comment] 2018-01-18 09:04
I'm getting the same error but in this case it seems that is because wordpress.org is down

**Comment by supermodo** [comment] 2018-01-19 04:09
Same issue

**Comment by dsvanidze** [comment] 2018-01-20 19:00
Same issue

**Comment by cinghaman** [comment] 2018-01-24 07:14
Any headway here, Getting this issue as well

**Comment by raylopro** [comment] 2018-01-24 08:53
same :(

**Comment by facundocastello** [comment] 2018-01-24 19:41
same

**Comment by jbmanos** [comment] 2018-01-26 01:22
same here, too

**Comment by softtama** [comment] 2018-01-31 04:34
For those who have a Jetpack plugin installed on Wordpress:
Eventually I can resolve the problem by reactivating (deactivate, then activate again) the Jetpack plugin. The error mentioned is gone now.

**Comment by lituokobe** [comment] 2018-02-01 02:18
same here too

**Comment by PCASME** [comment] 2018-02-01 17:28
+1

**Comment by hybridinteractive** [comment] 2018-02-12 17:46
+1

**Comment by creativesells** [comment] 2018-02-12 21:43
It works. Thank you softtama

**Comment by kraftbj** [comment] 2018-02-23 15:43
> For those who have a Jetpack plugin installed on Wordpress:
Eventually I can resolve the problem by reactivating (deactivate, then activate again) the Jetpack plugin. The error mentioned is gone now.

That doesn't directly fix the problem per se. The issue is if you're not actively logged into WordPress.com, the 403 is returned (as the socket is using your WordPress.com session). Cycling Jetpack works only because you're logging into WordPress.com as part of the process.

You can test this by having a site that works without the 403, logging out completely from wp.com, then seeing a 403. Log back into WordPress.com and all is good again.

**Comment by steffanhalv** [comment] 2018-03-03 12:15
Same here, using nginx with debian, wordpress and jetpack

Configs:

**/etc/nginx/nginx.conf**
```
user www-data;
worker_processes 3;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;
events {
        worker_connections 19000;
        multi_accept off;
        use epoll;
}
worker_rlimit_nofile 20000;
http {
        # Basic Settings
        keepalive_requests              120;
        keepalive_timeout               120s;
        send_timeout                    120;
        proxy_buffering                 off;
        proxy_http_version              1.1;
        proxy_read_timeout              180s;
        proxy_send_timeout              180s;
        proxy_set_header Connection "";
        proxy_set_header Origin "";
        client_body_buffer_size         32M;
        client_header_buffer_size       16k;
        client_max_body_size            180M;
        large_client_header_buffers     8 16k;
        client_body_timeout             180;
        client_header_timeout           180;
        fastcgi_read_timeout 3000;
        fastcgi_buffers 8 128k;
        fastcgi_buffer_size 256k;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        types_hash_max_size 2048;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        # SSL Settings
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # Dropping SSLv3, ref: POODLE
        ssl_prefer_server_ciphers on;

        # Logging Settings
        access_log off;
        error_log off;

        # Gzip Settings
        gzip off;
        
        # Virtual Host Configs
        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;
}

```

**/etc/nginx/sites-enabled/deafult**
```
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # SSL configuration
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        ssl_certificate /var/www/letsencrypt/live/stage.haagen.no/fullchain.pem;
        ssl_certificate_key /var/www/letsencrypt/live/stage.haagen.no/private.pem;
        ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;

        # Performance
        client_max_body_size    120M;
        root /var/www/html;
        index index.php index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                try_files $uri $uri/ /index.php?q=$uri&$args;
                proxy_buffering off;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   Host      $http_host;
                proxy_http_version 1.1;
                proxy_set_header Connection "";
                proxy_connect_timeout       300;
                proxy_send_timeout          300;
                proxy_read_timeout          300;
                send_timeout                300;
                fastcgi_read_timeout        300;
        }
        # pass PHP scripts to FastCGI server
        location ~ \.php$ {
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
                fastcgi_read_timeout    300;
        }
        # deny access to .htaccess files
        location ~ /\.ht {
                deny all;
        }
}
```

Any advice?

**Comment by mathiasdb** [comment] 2018-03-08 09:59
@softtama 's "solution" works for me (may not be the final solution, but at least the console error is gone for now.)

**Comment by vverloop** [comment] 2018-03-08 10:02
@matthiasdb it is not the solution!

**Comment by vverloop** [comment] 2018-03-08 10:03
Automattic is not answering to this topic! Stupid company!

**Comment by Barneybook** [comment] 2018-03-21 06:41
+1, how to fix this problem??

**Comment by Jany-M** [comment] 2018-03-27 17:59
Same issue here on several sites/servers.
Still nothing on this?

**Comment by jeherve** [comment] 2018-03-28 12:24
Thank you all for the reports. This is currently being tracked internally, in 604-gh-notifications-client.

Until the issue is resolved, I would recommend one of the following work-arounds:

- Log in to your WordPress.com account [here](https://wordpress.com/log-in).
- If you use the Jetpack plugin on your site, go to this page and deactivate the Notifications feature:
`https://yoursite.com/wp-admin/admin.php?page=jetpack_modules`

Closing as duplicate of 604-gh-notifications-client.

**Closed as completed by jeherve** 2018-03-28 12:24 UTC
Labels: duplicate

**Comment by shahalom** [comment] 2018-04-08 00:27
Thank You @jeherve ! Noticed the error in console after upgrade my site (https://mcqacademy.com/) with latest wp version. Now the error is invisible :+1:

**Comment by Developer-pro** [comment] 2018-05-15 10:30
Thanks For Helping!

**Comment by kraftbj** [comment] 2018-05-16 21:27
This issue is being tracked in https://github.com/Automattic/notifications-panel/issues/250
